#!/usr/bin/env bash
# https://github.com/koekeishiya/dotfiles/blob/master/yabai/yabairc
# https://github.com/koekeishiya/yabai/blob/master/examples/yabairc

# shellcheck disable=SC1090
source ~/.profile
# shellcheck disable=SC1090
source ~/bin/helpers.sh

# * Tiling Behavior
# stack/monocle by default
yabai -m config layout stack

# open new windows on right or bottom
yabai -m config window_placement second_child

# TODO does this actually work
# floating windows always on top
yabai -m config window_topmost on

# * Mouse Behavior
yabai -m config mouse_modifier cmd
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize
# swap rather than stack when dragging one bsp window onto another
yabai -m config mouse_drop_action swap

# * Appearance
# it's currently broken
# https://github.com/koekeishiya/yabai/issues/1732
# yabai -m config window_border on
yabai -m config window_border_hidpi on

yabai -m config window_shadow on

# window_animation_duration [<floating point number>]
# window_animation_frame_rate [<integer number>]

# ** Sizing
yabai -m config window_border_width "$WM_BORDER"

yabai -m config window_border_radius "$CORNER_RADIUS"

yabai -m config top_padding    "$WM_GAP"
yabai -m config bottom_padding "$WM_GAP"
yabai -m config left_padding   "$WM_GAP"
yabai -m config right_padding  "$WM_GAP"
yabai -m config window_gap     "$WM_GAP"

yabai -m config external_bar all:"$BAR_HEIGHT":0

# ** Color
wal_set_yabai_colors

# * Rules
# https://github.com/koekeishiya/yabai/issues/86
# https://github.com/koekeishiya/yabai/issues/587
# NOTE: only works with emacsclient if daemon was started through Emacs.app
# (e.g. open -a Emacs --args --daemon)
yabai -m rule --add app=Emacs manage=on

# https://github.com/koekeishiya/yabai/wiki/Commands#automation-with-rules-and-signals
# don't bother managing some apps that can't be resized
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Digital Color Meter$" manage=off
yabai -m rule --add app="^Cisco AnyConnect" manage=off

yabai -m rule --add title="^Microsoft Teams Notification$" manage=off

# some popup windows/notification windows don't have titles
yabai -m rule --add title="^$" manage=off

# * Create Spaces
yabei ensure_space 1 one
yabei ensure_space 2 two
yabei ensure_space 3 three
yabei ensure_space 4 four
yabei ensure_space 5 five
yabei ensure_space 6 six
yabei ensure_space 7 seven
yabei ensure_space 8 eight
yabei ensure_space 9 nine
yabei ensure_space 10 ten

# * Wallpaper
# TODO is this necessary?
# wal -R -n
if [[ -f ~/.cache/wallpaper ]]; then
	setallspaceswallpaper ~/.cache/wallpaper
fi

# * Signals
yabai -m signal --add event=window_created \
	  action="sketchybar -m --trigger yabai_window_created &> /dev/null"
yabai -m signal --add event=window_destroyed \
	  action="sketchybar -m --trigger yabai_window_destroyed &> /dev/null"
