#!/usr/bin/env bash
# https://github.com/koekeishiya/dotfiles/blob/master/yabai/yabairc
# https://github.com/koekeishiya/yabai/blob/master/examples/yabairc

# shellcheck disable=SC1090
source ~/.profile
# shellcheck disable=SC1090
source ~/bin/helpers.sh

# * Tiling Behavior
# stack/monocle by default
yabai -m config layout stack

# open new windows on right or bottom
yabai -m config window_placement second_child

# floating windows always on top
yabai -m config window_topmost on

# * Mouse Behavior
yabai -m config mouse_modfier cmd
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize
# swap rather than stack when dragging one bsp window onto another
yabai -m config mouse_drop_action swap

# * Appearance
yabai -m config window_border on
yabai -m config window_border_hidpi on

yabai -m config window_shadow on

# window_animation_duration [<floating point number>]
# window_animation_frame_rate [<integer number>]

# ** Sizing
yabai -m config window_border_width "$WM_BORDER"

yabai -m config window_border_radius "$CORNER_RADIUS"

yabai -m config top_padding    "$WM_GAP"
yabai -m config bottom_padding "$WM_GAP"
yabai -m config left_padding   "$WM_GAP"
yabai -m config right_padding  "$WM_GAP"
yabai -m config window_gap     "$WM_GAP"

# yabai -m config all:"$TOP_PADDING":0 external_bar

# ** Color
wal_set_yabai_colors

# * Rules
# https://github.com/koekeishiya/yabai/wiki/Commands#automation-with-rules-and-signals
# don't bother managing some apps that can't be resized
yabai -m rule --add app="^System Settings$" manage=off
# doesn't seem to be able to manage Outlook correctly...
# yabai -m rule --add app="^Outlook$" manage=off

# * Create Spaces
yabai -m space --create 1 --label one
yabai -m space --create 2 --label two
yabai -m space --create 3 --label three
yabai -m space --create 4 --label four
yabai -m space --create 5 --label five
yabai -m space --create 6 --label six
yabai -m space --create 7 --label seven
yabai -m space --create 8 --label eight
yabai -m space --create 9 --label nine
yabai -m space --create 10 --label ten

# * Wallpaper
# TODO is this necessary?
# wal -R -n
if [[ -f ~/.cache/wallpaper ]]; then
	setallspaceswallpaper ~/.cache/wallpaper
fi

