#!/usr/bin/env bash
# https://github.com/koekeishiya/dotfiles/blob/master/yabai/yabairc
# https://github.com/koekeishiya/yabai/blob/master/examples/yabairc

# * Tiling Behavior
# stack/monocle by default
yabai -m config layout stack

# open new windows on right or bottom
yabai -m config window_placement second_child

# floating windows always on top
yabai -m config window_topmost on

# * Mouse Behavior
yabai -m config mouse_modfier cmd
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize
# swap rather than stack when dragging one bsp window onto another
yabai -m config mouse_drop_action swap

# * Appearance
yabai -m config window_border on
yabai -m config window_border_hidpi on

yabai -m config window_shadow on

# window_animation_duration [<floating point number>]
# window_animation_frame_rate [<integer number>]

# ** Sizing
# TODO this is based on 4k, make it adaptive
# border=3
border=7
# padding=15
padding=30
radius=$(echo "(0.5 * $padding) / 1" | bc)

yabai -m config window_border_width "$border"

yabai -m config window_border_radius "$radius"

yabai -m config top_padding    "$padding"
yabai -m config bottom_padding "$padding"
yabai -m config left_padding   "$padding"
yabai -m config right_padding  "$padding"
yabai -m config window_gap     "$padding"

# yabai -m config all:40:0 external_bar

# ** Color
# active_window_border_color [0xAARRGGBB]
# normal_window_border_color [0xAARRGGBB]
# insert_feedback_color [0xAARRGGBB]

# * Rules
# https://github.com/koekeishiya/yabai/wiki/Commands#automation-with-rules-and-signals
# don't bother managing some apps that can't be resized
yabai -m rule --add app="^System Settings$" manage=off
# doesn't seem to be able to manage Outlook correctly...
# yabai -m rule --add app="^Outlook$" manage=off

# * Create Spaces
yabai -m space --create 1 --label one
yabai -m space --create 2 --label two
yabai -m space --create 3 --label three
yabai -m space --create 4 --label four
yabai -m space --create 5 --label five
yabai -m space --create 6 --label six
yabai -m space --create 7 --label seven
yabai -m space --create 8 --label eight
yabai -m space --create 9 --label nine
yabai -m space --create 10 --label ten
